import type { ModulePageConfig } from "@/components/dashboard/module-page";

export const dashboardPages: Record<string, ModulePageConfig> = {
  assets: {
    title: "Data List Aset",
    subtitle: "Kelola daftar aset, kode inventaris, status operasional, lokasi, dan kepemilikan aset.",
    primaryAction: "Tambah Aset",
    secondaryAction: "Import",
    stats: [
      { label: "Total Aset", value: "0", helper: "Semua aset aktif dan arsip." },
      { label: "Aset Aktif", value: "0", helper: "Siap digunakan atau sedang dipakai." },
      { label: "Perlu Audit", value: "0", helper: "Belum diverifikasi periode ini." },
      { label: "Low Stock", value: "0", helper: "Aset consumable di bawah threshold." },
    ],
    filters: ["Aktif", "Dipinjam", "Maintenance", "Disposal"],
    columns: ["Kode", "Nama Aset", "Kategori", "Lokasi", "Status", "PIC", "Aksi"],
    emptyTitle: "Belum ada data aset.",
    noteTitle: "Tahap berikutnya",
    note: "Tabel ini siap dihubungkan ke endpoint aset, import CSV, dan form CRUD.",
  },
  maintenance: {
    title: "Perawatan Aset",
    subtitle: "Pantau jadwal maintenance, pekerjaan berjalan, biaya, vendor, dan hasil perawatan.",
    primaryAction: "Tambah Perawatan",
    secondaryAction: "Export",
    stats: [
      { label: "Terbuka", value: "0", helper: "Request planned atau in progress." },
      { label: "Jatuh Tempo", value: "0", helper: "Perlu tindakan dalam 7 hari." },
      { label: "Selesai Bulan Ini", value: "0", helper: "Maintenance closed periode berjalan." },
      { label: "Estimasi Biaya", value: "0", helper: "Akumulasi pekerjaan aktif." },
    ],
    filters: ["Planned", "In Progress", "Done", "Overdue"],
    columns: ["Aset", "Jenis", "Vendor", "Jadwal", "Biaya", "Status", "Catatan"],
    emptyTitle: "Belum ada data perawatan.",
    noteTitle: "Kontrol maintenance",
    note: "Halaman ini akan menampung reminder, histori pekerjaan, dan approval biaya maintenance.",
  },
  reports: {
    title: "Reports",
    subtitle: "Konsolidasi laporan aset, audit, movement, disposal, maintenance, dan warranty.",
    primaryAction: "Buat Laporan",
    secondaryAction: "Export",
    stats: [
      { label: "Template Aktif", value: "0", helper: "Format laporan tersimpan." },
      { label: "Export Bulan Ini", value: "0", helper: "File yang sudah dibuat." },
      { label: "Audit Issues", value: "0", helper: "Temuan yang perlu disertakan." },
      { label: "Approval Pending", value: "0", helper: "Menunggu keputusan." },
    ],
    filters: ["Asset", "Audit", "Movement", "Disposal", "Maintenance"],
    columns: ["Nama Laporan", "Periode", "Format", "Dibuat Oleh", "Waktu", "Status"],
    emptyTitle: "Belum ada laporan dibuat.",
    noteTitle: "Pusat laporan",
    note: "Nanti setiap modul dapat mengirim dataset ke halaman ini untuk export PDF, Excel, atau CSV.",
  },
  charts: {
    title: "Charts",
    subtitle: "Area visualisasi untuk tren aset, distribusi status, lokasi, kategori, dan aktivitas operasional.",
    primaryAction: "Tambah Widget",
    secondaryAction: "Export",
    stats: [
      { label: "Widget Aktif", value: "0", helper: "Grafik yang tampil di dashboard." },
      { label: "Dataset", value: "0", helper: "Sumber data siap dipakai." },
      { label: "Refresh Terjadwal", value: "0", helper: "Visual yang auto-update." },
      { label: "Alert Chart", value: "0", helper: "Grafik dengan ambang batas." },
    ],
    filters: ["Asset", "Movement", "Audit", "Maintenance", "Cost"],
    columns: ["Nama Chart", "Dataset", "Tipe", "Periode", "Owner", "Status", "Aksi"],
    emptyTitle: "Belum ada konfigurasi chart.",
    noteTitle: "Visual analytics",
    note: "Halaman ini siap menampung chart builder dan dashboard widget setelah endpoint data tersedia.",
  },
  approvals: {
    title: "Approval Pending",
    subtitle: "Kelola antrean approval untuk movement, disposal, maintenance, dan perubahan data penting.",
    primaryAction: "Buat Request",
    secondaryAction: "Export",
    stats: [
      { label: "Pending", value: "0", helper: "Menunggu keputusan approver." },
      { label: "Approved", value: "0", helper: "Disetujui periode berjalan." },
      { label: "Rejected", value: "0", helper: "Ditolak dengan catatan." },
      { label: "SLA Lewat", value: "0", helper: "Melewati target respons." },
    ],
    filters: ["Movement", "Disposal", "Maintenance", "High Value", "Overdue"],
    columns: ["Tipe", "Referensi", "Requester", "Approver", "Dibuat", "SLA", "Status", "Aksi"],
    emptyTitle: "Tidak ada approval pending.",
    noteTitle: "Workflow approval",
    note: "Layout ini akan dipakai untuk approve, reject, komentar, dan histori keputusan.",
  },
  security: {
    title: "Security",
    subtitle: "Atur akses pengguna, role, permission, sesi, audit trail, dan kontrol keamanan sistem.",
    primaryAction: "Tambah Role",
    secondaryAction: "Export",
    stats: [
      { label: "User Aktif", value: "0", helper: "Akun yang dapat login." },
      { label: "Role", value: "0", helper: "Grup hak akses tersedia." },
      { label: "Permission", value: "0", helper: "Aksi yang dapat dibatasi." },
      { label: "Sesi Aktif", value: "0", helper: "Login yang sedang berjalan." },
    ],
    filters: ["Users", "Roles", "Permissions", "2FA", "Audit Log"],
    columns: ["Nama", "Email", "Role", "2FA", "Last Login", "Status", "Aksi"],
    emptyTitle: "Belum ada data security.",
    noteTitle: "Kontrol akses",
    note: "Halaman ini menjadi fondasi user management, role management, permission, dan audit login.",
  },
  settings: {
    title: "Setting System",
    subtitle: "Kelola konfigurasi aplikasi, identitas sistem, notifikasi, threshold stok, dan preferensi workflow.",
    primaryAction: "Simpan Setting",
    secondaryAction: "Backup",
    stats: [
      { label: "Konfigurasi", value: "0", helper: "Parameter sistem tersedia." },
      { label: "Notifikasi", value: "0", helper: "Channel reminder aktif." },
      { label: "Threshold", value: "0", helper: "Batas stok dan SLA." },
      { label: "Integrasi", value: "0", helper: "Webhook atau API aktif." },
    ],
    filters: ["General", "Notification", "Workflow", "Import", "Integration"],
    columns: ["Nama Setting", "Group", "Value", "Tipe", "Terakhir Diubah", "Status", "Aksi"],
    emptyTitle: "Belum ada konfigurasi setting.",
    noteTitle: "Konfigurasi sistem",
    note: "Setting akan mengontrol default aplikasi, reminder garansi, low stock, SLA, dan mode maintenance.",
  },
  archive: {
    title: "Archive",
    subtitle: "Pantau aset arsip, soft delete, disposal final, dan data yang bisa dipulihkan.",
    primaryAction: "Restore Terpilih",
    secondaryAction: "Export",
    stats: [
      { label: "Arsip", value: "0", helper: "Data yang tidak aktif." },
      { label: "Trash", value: "0", helper: "Data soft deleted." },
      { label: "Disposal Final", value: "0", helper: "Aset yang selesai dihapus." },
      { label: "Retensi", value: "0", helper: "Melewati masa penyimpanan." },
    ],
    filters: ["Archived", "Trash", "Disposed", "Restorable", "Expired Retention"],
    columns: ["Tipe Data", "Referensi", "Nama", "Alasan", "Diarsipkan Oleh", "Waktu", "Aksi"],
    emptyTitle: "Belum ada data arsip.",
    noteTitle: "Retensi data",
    note: "Archive akan dipakai untuk restore, permanent delete, dan pelacakan aset nonaktif.",
  },
};

export const masterPages: Record<string, ModulePageConfig> = {
  "asset-statuses": {
    title: "Status Aset",
    subtitle: "Atur status siklus hidup aset seperti aktif, dipinjam, rusak, maintenance, disposal, dan arsip.",
    primaryAction: "Tambah Status",
    secondaryAction: "Export",
    stats: [
      { label: "Total Status", value: "0", helper: "Status yang tersedia." },
      { label: "Dipakai Asset", value: "0", helper: "Status sudah terhubung aset." },
      { label: "Default", value: "0", helper: "Status awal saat aset dibuat." },
      { label: "Nonaktif", value: "0", helper: "Status disembunyikan dari pilihan." },
    ],
    filters: ["Aktif", "Default", "System", "Custom"],
    columns: ["Nama Status", "Kode", "Warna", "Default", "Digunakan", "Aksi"],
    emptyTitle: "Belum ada data status aset.",
    noteTitle: "Master status",
    note: "Gunakan status untuk mengontrol workflow movement, audit, maintenance, dan disposal.",
  },
  "asset-classes": {
    title: "Kelas Aset",
    subtitle: "Kelompokkan aset berdasarkan kelas pengelolaan, prioritas, nilai, atau risiko operasional.",
    primaryAction: "Tambah Kelas",
    secondaryAction: "Export",
    stats: [
      { label: "Total Kelas", value: "0", helper: "Kelas aset yang terdaftar." },
      { label: "Prioritas Tinggi", value: "0", helper: "Kelas dengan kontrol ketat." },
      { label: "Digunakan", value: "0", helper: "Kelas terhubung ke aset." },
      { label: "Nonaktif", value: "0", helper: "Kelas tidak tampil di form." },
    ],
    filters: ["Aktif", "High Value", "Operational", "Consumable"],
    columns: ["Nama Kelas", "Kode", "Prioritas", "Deskripsi", "Digunakan", "Aksi"],
    emptyTitle: "Belum ada data kelas aset.",
    noteTitle: "Klasifikasi aset",
    note: "Kelas aset membantu menentukan aturan audit, approval, dan pelaporan.",
  },
  units: {
    title: "Satuan Unit Aset",
    subtitle: "Kelola satuan aset untuk stok, consumable, dan item inventaris yang dihitung berulang.",
    primaryAction: "Tambah Unit",
    secondaryAction: "Export",
    stats: [
      { label: "Total Unit", value: "0", helper: "Satuan tersedia." },
      { label: "Dipakai", value: "0", helper: "Satuan terhubung aset." },
      { label: "Consumable", value: "0", helper: "Satuan untuk stok habis pakai." },
      { label: "Nonaktif", value: "0", helper: "Tidak tampil di form." },
    ],
    filters: ["Aktif", "Consumable", "Fixed Asset"],
    columns: ["Nama Unit", "Kode", "Tipe", "Deskripsi", "Digunakan", "Aksi"],
    emptyTitle: "Belum ada data satuan unit.",
    noteTitle: "Satuan stok",
    note: "Unit akan dipakai untuk perhitungan stok, threshold, dan laporan aset consumable.",
  },
  departments: {
    title: "Departemen",
    subtitle: "Kelola departemen pemilik atau pengguna aset untuk tracking biaya dan tanggung jawab.",
    primaryAction: "Tambah Departemen",
    secondaryAction: "Export",
    stats: [
      { label: "Total Departemen", value: "0", helper: "Departemen terdaftar." },
      { label: "Memiliki Aset", value: "0", helper: "Departemen aktif memakai aset." },
      { label: "PIC Aktif", value: "0", helper: "Penanggung jawab terhubung." },
      { label: "Nonaktif", value: "0", helper: "Departemen tidak digunakan." },
    ],
    filters: ["Aktif", "Operasional", "Support", "Finance"],
    columns: ["Nama Departemen", "Kode", "Manager", "Lokasi", "Total Aset", "Aksi"],
    emptyTitle: "Belum ada data departemen.",
    noteTitle: "Ownership aset",
    note: "Departemen akan menjadi dasar mapping kepemilikan, cost center, dan approval.",
  },
  "person-in-charge": {
    title: "Penanggung Jawab Aset",
    subtitle: "Kelola PIC untuk audit, movement, maintenance, dan eskalasi aset bermasalah.",
    primaryAction: "Tambah PIC",
    secondaryAction: "Export",
    stats: [
      { label: "Total PIC", value: "0", helper: "Penanggung jawab terdaftar." },
      { label: "Aktif", value: "0", helper: "Masih menerima assignment." },
      { label: "Assignment", value: "0", helper: "Aset sedang ditangani." },
      { label: "Pending Review", value: "0", helper: "Data PIC perlu dicek." },
    ],
    filters: ["Aktif", "Auditor", "Maintenance", "Approver"],
    columns: ["Nama", "Departemen", "Email", "Telepon", "Role", "Aset", "Aksi"],
    emptyTitle: "Belum ada data PIC.",
    noteTitle: "Tanggung jawab aset",
    note: "PIC akan dipakai untuk reminder, eskalasi, dan workflow persetujuan.",
  },
  "asset-users": {
    title: "Pengguna Aset",
    subtitle: "Kelola pengguna akhir aset untuk peminjaman, movement, dan histori penggunaan.",
    primaryAction: "Tambah Pengguna",
    secondaryAction: "Export",
    stats: [
      { label: "Total Pengguna", value: "0", helper: "User aset terdaftar." },
      { label: "Memegang Aset", value: "0", helper: "Punya aset aktif." },
      { label: "Movement Aktif", value: "0", helper: "Sedang proses perpindahan." },
      { label: "Nonaktif", value: "0", helper: "Tidak tampil di pilihan." },
    ],
    filters: ["Aktif", "Karyawan", "Kontraktor", "Departemen"],
    columns: ["Nama", "NIK", "Departemen", "Email", "Aset Aktif", "Status", "Aksi"],
    emptyTitle: "Belum ada data pengguna aset.",
    noteTitle: "Histori pemakai",
    note: "Pengguna aset menjadi referensi utama untuk riwayat pemakaian dan serah-terima.",
  },
  "asset-categories": {
    title: "Kategori Aset",
    subtitle: "Kelola kategori aset untuk struktur inventaris, penomoran, dan laporan.",
    primaryAction: "Tambah Kategori",
    secondaryAction: "Export",
    stats: [
      { label: "Total Kategori", value: "0", helper: "Kategori terdaftar." },
      { label: "Subkategori", value: "0", helper: "Kategori turunan." },
      { label: "Digunakan", value: "0", helper: "Terhubung ke aset." },
      { label: "Nonaktif", value: "0", helper: "Tidak tampil di form." },
    ],
    filters: ["Aktif", "IT", "Furniture", "Vehicle", "Consumable"],
    columns: ["Nama Kategori", "Parent", "Kode Prefix", "Depresiasi", "Digunakan", "Aksi"],
    emptyTitle: "Belum ada data kategori aset.",
    noteTitle: "Struktur katalog",
    note: "Kategori dapat dipakai untuk generate kode aset dan pemetaan laporan.",
  },
  "asset-locations": {
    title: "Lokasi Aset",
    subtitle: "Kelola lokasi fisik aset dari site, gedung, lantai, ruang, sampai area penyimpanan.",
    primaryAction: "Tambah Lokasi",
    secondaryAction: "Export",
    stats: [
      { label: "Total Lokasi", value: "0", helper: "Lokasi terdaftar." },
      { label: "Memiliki Aset", value: "0", helper: "Lokasi berisi aset aktif." },
      { label: "Gudang", value: "0", helper: "Area penyimpanan stok." },
      { label: "Nonaktif", value: "0", helper: "Tidak dipakai lagi." },
    ],
    filters: ["Aktif", "Office", "Warehouse", "Remote Site"],
    columns: ["Nama Lokasi", "Kode", "Parent", "Alamat", "Total Aset", "Aksi"],
    emptyTitle: "Belum ada data lokasi aset.",
    noteTitle: "Tracking lokasi",
    note: "Lokasi akan dipakai untuk movement, audit fisik, dan peta distribusi aset.",
  },
  warranties: {
    title: "Masa Garansi Aset",
    subtitle: "Kelola informasi garansi, vendor, tanggal kedaluwarsa, dan reminder klaim.",
    primaryAction: "Tambah Garansi",
    secondaryAction: "Export",
    stats: [
      { label: "Total Garansi", value: "0", helper: "Data garansi tersimpan." },
      { label: "Akan Habis", value: "0", helper: "Berakhir dalam 30 hari." },
      { label: "Expired", value: "0", helper: "Sudah melewati masa garansi." },
      { label: "Klaim Aktif", value: "0", helper: "Sedang proses vendor." },
    ],
    filters: ["Aktif", "Akan Habis", "Expired", "Claim"],
    columns: ["Aset", "Vendor", "No. Garansi", "Mulai", "Berakhir", "Status", "Aksi"],
    emptyTitle: "Belum ada data garansi.",
    noteTitle: "Reminder garansi",
    note: "Data garansi akan memicu notifikasi dan membantu keputusan repair atau replacement.",
  },
  "vendor-contracts": {
    title: "Vendor & Kontrak Aset",
    subtitle: "Kelola vendor, nomor kontrak, periode kontrak, SLA, dan catatan layanan aset.",
    primaryAction: "Tambah Kontrak",
    secondaryAction: "Export",
    stats: [
      { label: "Total Kontrak", value: "0", helper: "Kontrak vendor tersimpan." },
      { label: "Aktif", value: "0", helper: "Kontrak dalam periode berjalan." },
      { label: "Akan Habis", value: "0", helper: "Perlu review perpanjangan." },
      { label: "Dipakai Aset", value: "0", helper: "Terhubung ke aset." },
    ],
    filters: ["Aktif", "Akan Habis", "Expired", "SLA"],
    columns: ["Vendor", "No. Kontrak", "Mulai", "Berakhir", "SLA", "Aksi"],
    emptyTitle: "Belum ada data vendor contract.",
    noteTitle: "Vendor contract",
    note: "Kontrak vendor akan dipakai untuk mapping aset, SLA, warranty, dan pengelolaan layanan.",
  },
};

export const transactionPages: Record<string, ModulePageConfig> = {
  movements: {
    title: "Movement Aset",
    subtitle: "Kelola perpindahan aset antar pengguna, departemen, lokasi, dan gudang.",
    primaryAction: "Tambah Movement",
    secondaryAction: "Export",
    stats: [
      { label: "Draft", value: "0", helper: "Movement belum diajukan." },
      { label: "Pending Approval", value: "0", helper: "Menunggu keputusan." },
      { label: "Approved", value: "0", helper: "Siap diproses." },
      { label: "Completed", value: "0", helper: "Perpindahan selesai." },
    ],
    filters: ["Draft", "Pending", "Approved", "Rejected", "Completed"],
    columns: ["Kode", "Aset", "Dari", "Ke", "Requester", "Status", "Waktu"],
    emptyTitle: "Belum ada data movement.",
    noteTitle: "Workflow movement",
    note: "Movement akan terhubung ke approval dan memperbarui lokasi atau pengguna aset setelah selesai.",
  },
  disposals: {
    title: "Disposal Aset",
    subtitle: "Kelola penghapusan, penjualan, donasi, atau disposal aset yang tidak lagi digunakan.",
    primaryAction: "Tambah Disposal",
    secondaryAction: "Export",
    stats: [
      { label: "Draft", value: "0", helper: "Disposal belum diajukan." },
      { label: "Pending Approval", value: "0", helper: "Menunggu persetujuan." },
      { label: "Approved", value: "0", helper: "Siap dieksekusi." },
      { label: "Reversed", value: "0", helper: "Disposal dibatalkan." },
    ],
    filters: ["Draft", "Pending", "Approved", "Disposed", "Reversed"],
    columns: ["Kode", "Aset", "Alasan", "Nilai", "Requester", "Status", "Waktu"],
    emptyTitle: "Belum ada data disposal.",
    noteTitle: "Kontrol disposal",
    note: "Disposal akan memindahkan aset ke arsip dan mencatat alasan serta dokumen pendukung.",
  },
  audits: {
    title: "Audit Aset",
    subtitle: "Catat hasil audit fisik aset, kondisi, lokasi aktual, dan temuan missing atau damaged.",
    primaryAction: "Tambah Audit",
    secondaryAction: "Export",
    stats: [
      { label: "Audit Bulan Ini", value: "0", helper: "Pemeriksaan tercatat." },
      { label: "Match", value: "0", helper: "Data sesuai kondisi fisik." },
      { label: "Missing", value: "0", helper: "Aset tidak ditemukan." },
      { label: "Damaged", value: "0", helper: "Aset bermasalah." },
    ],
    filters: ["Match", "Mismatch", "Missing", "Damaged"],
    columns: ["Kode Audit", "Aset", "Lokasi Aktual", "Kondisi", "Auditor", "Waktu", "Catatan"],
    emptyTitle: "Belum ada data audit.",
    noteTitle: "Audit fisik",
    note: "Audit akan menjadi sumber temuan untuk tindak lanjut maintenance, movement, atau write-off.",
  },
};
