import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import * as XLSX from "xlsx";
import ExcelJS from "exceljs";
import { parseBulkFile, workbookBuffer } from "../src/lib/asset-bulk-format";
import { previewBulk, confirmBulk, previewDelete, bulkTemplate, bulkReport } from "../src/lib/asset-bulk";
import { prisma } from "../src/lib/prisma";

const csv = (text: string) => parseBulkFile(Buffer.from(text), "test.csv", "IMPORT");
assert.throws(() => parseBulkFile(Buffer.from("hello"), "file.exe", "IMPORT"));
assert.throws(() => parseBulkFile(Buffer.from("hello"), "file.xlsx", "IMPORT"));
assert.throws(() => csv("Code,Name\nA,Laptop"));
assert.throws(() => csv("Asset Code,Asset Name,Asset Code\nA,Laptop,A"));
assert.throws(() => csv("Asset Code,Asset Name\n"));
assert.throws(() => csv("Asset Code,Asset Name\n" + Array.from({ length: 201 }, (_, i) => `${i},Laptop`).join("\n")));
assert.equal(csv("Asset Code,Asset Name\nA,Laptop\nA,Laptop")[1].result, "Duplicate");
assert.equal(csv("Asset Code,Asset Name,Serial Number\nA,Laptop,SN\nB,Laptop,SN")[1].result, "Duplicate");
assert.equal(csv("Asset Code,Asset Name\nA,Laptop\nB,Laptop")[1].result, "Ready");
assert.equal(csv("Asset Code,Asset Name,Purchase Date\nA,Laptop,2026-02-30")[0].result, "Invalid");
assert.equal(csv("Asset Code,Asset Name,Cost\nA,Laptop,-1")[0].result, "Invalid");
const workbook = workbookBuffer([{ name: "Import Asset", rows: [["Asset Code", "Asset Name"], ["A", "Laptop"]] }]);
assert.equal(parseBulkFile(workbook, "template.xlsx", "IMPORT")[0].result, "Ready");
const formulaBook = XLSX.read(workbook, { type: "buffer" });
formulaBook.Sheets["Import Asset"].B2.f = '"Laptop"';
assert.equal(parseBulkFile(XLSX.write(formulaBook, { type: "buffer", bookType: "xlsx" }), "formula.xlsx", "IMPORT")[0].result, "Invalid");
console.log("PASS: parser, format/header/limit/date/cost/formula validation, in-file duplicates, XLSX roundtrip");

// Opt in: tests create isolated records and remove only those records afterward.
if (process.argv.includes("--database")) {
  const prefix = `BULK-TEST-${randomUUID()}`;
  const user = await prisma.user.create({ data: { name: prefix, email: `${prefix}@example.invalid`, password: "not-a-login-hash" } });
  const codes = ["A", "B", "C", "D"].map(suffix => `${prefix}-${suffix}`);
  const masterIds: string[] = [];
  try {
    const category = await prisma.assetCategory.create({ data: { code: `${prefix}-CAT`, name: `${prefix} Category` } });
    masterIds.push(category.id);
    const importTemplate = new ExcelJS.Workbook();
    await importTemplate.xlsx.load(await bulkTemplate("IMPORT") as unknown as ExcelJS.Buffer);
    assert.deepEqual(importTemplate.worksheets.map(s => s.name), ["Import Asset", "Reference Data", "Instructions"]);
    for (const address of ["C2", "D2", "E2", "F2", "G2", "H2", "I2", "C201"]) {
      const validation = importTemplate.getWorksheet("Import Asset")!.getCell(address).dataValidation;
      assert.equal(validation.type, "list");
      assert.equal(validation.errorStyle, "stop");
      assert.match(String(validation.formulae?.[0]), /^Master_/);
      assert.ok(importTemplate.definedNames.getRanges(String(validation.formulae![0])).ranges[0].includes("Reference Data"));
    }
    const referenceValues = importTemplate.getWorksheet("Reference Data")!.getColumn(2).values;
    assert.ok(referenceValues.includes(category.name));
    const fresh = await prisma.assetCategory.create({ data: { code: `${prefix}-NEW`, name: `${prefix} New Category` } });
    masterIds.push(fresh.id);
    const freshTemplate = new ExcelJS.Workbook();
    await freshTemplate.xlsx.load(await bulkTemplate("IMPORT") as unknown as ExcelJS.Buffer);
    assert.ok(!referenceValues.includes(fresh.name));
    assert.ok(freshTemplate.getWorksheet("Reference Data")!.getColumn(2).values.includes(fresh.name));
    const input = importTemplate.getWorksheet("Import Asset")!;
    input.getCell("A2").value = codes[0]; input.getCell("B2").value = "Laptop"; input.getCell("C2").value = category.name;
    const roundtrip = parseBulkFile(Buffer.from(await importTemplate.xlsx.writeBuffer()), "dropdown.xlsx", "IMPORT");
    assert.equal(roundtrip.length, 1, "Validation-only blank rows must be ignored");
    assert.equal(roundtrip[0].values.Category, category.name);
    const initial = csv(`Asset Code,Asset Name,Serial Number,Category\n${codes[0]},Laptop,${prefix}-SN,${category.name}\n${codes[1]},Laptop,${prefix}-SN,\n${codes[2]},,,`);
    const preview = await previewBulk(user.id, "IMPORT", "test.csv", initial);
    assert.equal(await prisma.asset.count({ where: { code: { in: codes } } }), 0, "Preview must not insert");
    const done = await confirmBulk(user.id, preview.id);
    assert.deepEqual(done.rows.map(r => r.result), ["Success", "Duplicate", "Invalid"]);
    await confirmBulk(user.id, preview.id);
    assert.equal(await prisma.asset.count({ where: { code: { in: codes } } }), 1, "Replay must not insert twice");
    await assert.rejects(confirmBulk(randomUUID(), preview.id));
    await assert.rejects(bulkReport(randomUUID(), preview.id));
    const dup = await previewBulk(user.id, "IMPORT", "duplicates.csv", csv(`Asset Code,Asset Name,Serial Number\n${codes[0]},Other,\n${codes[1]},Other,${prefix}-SN`));
    assert.deepEqual(dup.rows.map(r => r.result), ["Duplicate", "Duplicate"]);
    const badRelation = await previewBulk(user.id, "IMPORT", "bad.csv", csv(`Asset Code,Asset Name,Category\n${codes[2]},Laptop,${prefix}-missing`));
    assert.equal(badRelation.rows[0].result, "Invalid");
    const asset = await prisma.asset.findUniqueOrThrow({ where: { code: codes[0] } });
    assert.equal(asset.assetCategoryId, category.id, "Master name maps to FK ID");
    const template = XLSX.read(await bulkTemplate("UPDATE", [asset.id]), { type: "buffer" });
    assert.deepEqual(template.SheetNames, ["Update Asset", "Reference Data", "Instructions"]);
    assert.equal(template.Sheets["Update Asset"].A2.v, asset.code);
    assert.equal(template.Sheets["Update Asset"].C2.v, category.name);
    const masterPreview = await previewBulk(user.id, "IMPORT", "master.csv", csv(`Asset Code,Asset Name,Category\n${codes[1]},Laptop,${fresh.name}`));
    await prisma.assetCategory.update({ where: { id: fresh.id }, data: { name: `${fresh.name} renamed` } });
    const changedMaster = await confirmBulk(user.id, masterPreview.id);
    assert.equal(changedMaster.rows[0].result, "Failed");
    assert.equal(changedMaster.rows[0].reason, `Category '${fresh.name}' does not exist in master data.`);
    const rebound = await previewBulk(user.id, "IMPORT", "master.csv", csv(`Asset Code,Asset Name,Category\n${codes[1]},Laptop,${fresh.name} renamed`));
    await prisma.assetCategory.delete({ where: { id: fresh.id } });
    const replacement = await prisma.assetCategory.create({ data: { code: fresh.code, name: `${fresh.name} renamed` } });
    masterIds.push(replacement.id);
    assert.match((await confirmBulk(user.id, rebound.id)).rows[0].reason, /Master data berubah/);
    const ambiguous = await prisma.assetCategory.create({ data: { code: `${prefix}-AMB`, name: category.name } });
    masterIds.push(ambiguous.id);
    const ambiguity = await previewBulk(user.id, "IMPORT", "ambiguous.csv", csv(`Asset Code,Asset Name,Category\n${codes[1]},Laptop,${category.name}`));
    assert.equal(ambiguity.rows[0].result, "Invalid");
    assert.match(ambiguity.rows[0].reason, /ambiguous/);
    await prisma.assetCategory.delete({ where: { id: ambiguous.id } });
    const updateRows = () => parseBulkFile(Buffer.from(`Asset Code,Asset Name,Description\n${codes[0]},Updated Laptop,New description`), "update.csv", "UPDATE");
    const outside = await previewBulk(user.id, "UPDATE", "update.csv", updateRows(), [randomUUID()]);
    assert.equal(outside.rows[0].result, "Invalid");
    const update = await previewBulk(user.id, "UPDATE", "update.csv", updateRows(), [asset.id]);
    assert.ok(update.rows[0].changes.some(c => c.field === "Asset Name" && c.before === "Laptop" && c.after === "Updated Laptop"));
    await confirmBulk(user.id, update.id);
    assert.equal((await prisma.asset.findUniqueOrThrow({ where: { id: asset.id } })).name, "Updated Laptop");
    const stale = await previewBulk(user.id, "UPDATE", "update.csv", updateRows(), [asset.id]);
    await prisma.asset.update({ where: { id: asset.id }, data: { name: "Concurrent change" } });
    assert.equal((await confirmBulk(user.id, stale.id)).rows[0].result, "Failed");
    assert.equal((await prisma.asset.findUniqueOrThrow({ where: { id: asset.id } })).name, "Concurrent change");
    // Two independent previews of the same serial must not both insert.
    const raceRows = (code: string) => csv(`Asset Code,Asset Name,Serial Number\n${code},Laptop,${prefix}-RACE`);
    const race1 = await previewBulk(user.id, "IMPORT", "race1.csv", raceRows(codes[2]));
    const race2 = await previewBulk(user.id, "IMPORT", "race2.csv", raceRows(codes[3]));
    const race = await Promise.all([confirmBulk(user.id, race1.id), confirmBulk(user.id, race2.id)]);
    assert.deepEqual(race.map(r => r.rows[0].result).sort(), ["Duplicate", "Success"]);
    const deletion = await previewDelete(user.id, [asset.id]);
    assert.equal((await prisma.asset.findUniqueOrThrow({ where: { id: asset.id } })).deletedAt, null);
    assert.equal((await confirmBulk(user.id, deletion.id)).rows[0].result, "Success");
    assert.ok((await prisma.asset.findUniqueOrThrow({ where: { id: asset.id } })).deletedAt);
    assert.equal(await prisma.assetHistory.count({ where: { assetId: asset.id, changedById: user.id } }), 3);
    const report = XLSX.read(await bulkReport(user.id, preview.id), { type: "buffer" });
    assert.equal(report.Sheets.Result.D2.v, "Success");
    const audit = await prisma.assetBulkJob.findUniqueOrThrow({ where: { id: preview.id } });
    assert.deepEqual(audit.summary, { total: 3, success: 1, duplicate: 1, invalid: 1, failed: 0 });
    console.log("PASS: preview/no writes, partial import, DB duplicates, concurrent serial conflict, replay/ownership, relations, update template/changes/scope, stale update, soft delete, report, audit");
    console.log("PASS: database dropdowns/named ranges, fresh reference data, XLSX dropdown roundtrip, name-to-FK mapping, renamed and ambiguous master rejection");
  } finally {
    await prisma.asset.deleteMany({ where: { code: { in: codes } } });
    await prisma.assetBulkJob.deleteMany({ where: { userId: user.id } });
    await prisma.assetCategory.deleteMany({ where: { id: { in: masterIds } } });
    await prisma.user.delete({ where: { id: user.id } });
    await prisma.$disconnect();
  }
}
